type: api-service
description: dummy api service used for testing setup only - does not run
author: test-author

messages:
  sends:
  receives:

development:
  ports:
    - 80
  scripts:
    run: echo "does not run"
