type: todo-service
description: dummy todo service used for testing set up - does not run
author: test-author

setup: yarn install
startup:
  command: echo "does not run"
  online-text: does not run
tests: echo "no tests here"

messages:
  receives:
    - todo.create
  sends:
    - todo.created

dependencies:
  name: 'mongo'
  version: '3.4.0'
  config:
    volumes:
      - '{{EXO_DATA_PATH}}:/data/db'
    ports:
      - '27017:27017'
    online-text: 'waiting for connections'
