title: another service with tests failing
description: has some feature specs
author: exospheredev

setup: echo 'setting up the tweets service'
startup:
  command: echo 'starting the tweets service'
  online-text: starting the tweets service
tests: echo 'running tests for tweets service'

messages:
  receives:
  sends:
