name: Simplest possible Exosphere web application
description: For making testing fast
author: exospheredev
version: '1.0'

dependencies:
  - type: exocom
    version: 0.22.0

services:
  public:
    web:
      location: ./web
