type: failing-tests-service-1
description: has some failing feature specs
author: exospheredev

setup: echo 'setting up the users service'
startup:
  command: echo 'starting the users service'
  online-text: starting the users service
tests: ./run-tests

messages:
  receives:
  sends:
