type: _____serviceType_____
description: _____description_____
author: _____author_____

setup: glide install && go get github.com/DATA-DOG/godog
startup:
  command: go run server.go
  online-text: online at port
tests: go test

messages:
  receives:
    - ping
  sends:
    - pong

dependencies:
