name: external-dependency
description: For testing booting up dependencies
author: exospheredev
version: '1.0'

development:
  dependencies:
    - name: exocom
      version: 0.26.1

services:
  mongo:
    location: ./mongo
