name: Exosphere-application-with-a-third-party-dependency
description: For testing booting up dependencies
author: exospheredev
version: '1.0'

dependencies:
  - name: exocom
    version: 0.23.0

services:
  public:
    mongo:
      location: ./mongo
