name: application with an external service
description: skeleton app using only an external service
version: '1.0.0'

bus:
  type: exocom
  version: latest

  
services:
  public:
    web:
      location: ../web-service
