type: test-mongoDB-service
description: generic mongoDB storage service
author: exospheredev

setup: yarn install
startup:
  command: node_modules/exoservice/bin/exo-js
  online-text: online at port

messages:
  receives:
    - mongo.list
    - mongo.create
  sends:
    - mongo.listed
    - mongo.created
