environment:
  nodejs_version: "6.5.0"

install:
  - ps: Install-Product node $env:nodejs_version
  - yarn install
  - git config --global user.name "Appveyor"
  - git config --global user.email ci@appveyor.com

test_script:
  - node --version
  - yarn --version
  - bin\spec.cmd

build: off
