title: _____serviceName_____
description: _____description_____
author: _____author_____

setup: yarn install
startup:
  command: node app
  online-text: HTML server is running

messages:
  sends:
  receives:

docker:
  link:
  publish:
