title: _____serviceName_____
description: _____description_____
author: _____author_____

setup: npm install --loglevel error --depth 0
startup:
  command: node app
  online-text: HTML server is running

messages:
  sends:
  receives:

docker:
  dependencies:
  publish:
