name: Example application
description: Demonstrates basic Exosphere application startup
version: '1.0'

dependencies:
  - name: exocom
    version: 0.21.8
    silent: true

services:
  public:
    web:
      location: ./web-server
  private:
    users:
      namespace: mongo
      location: ./mongo-service
      silent: true
