type: crasher-service
description: crashes on server request
author: exospheredev

setup: echo 'setting up ... done'
startup:
  command: node server.js
  online-text: web server running at port


messages:
  sends:
  receives:
