name: app-with-external-docker-images
description: An application whose services are Dockerhub images
version: 0.0.0

dependencies:
  - type: exocom
    version: 0.21.8

services:
  public:
    external-service:
      docker-image: originate/test-web-server
