type: _____serviceType_____
description: _____description_____
author: _____author_____

setup: yarn install
startup:
  command: ./node_modules/livescript/bin/lsc ./index.ls
  online-text: HTML server is running

messages:
  sends:
  receives:

dependencies:

docker:
  publish:
    - '3000:3000'
