title: test service that keeps running
description: generic MongoDB storage service
author: exospheredev

setup: echo "installing dependencies for 'runner' service"
startup:
  command: ./server
  online-text: running

messages:
  receives:
  sends:
