name: failing-setup
description: For testing errors during setup
version: '1.0'

development:
  dependencies:
    - name: exocom
      version: 0.26.1

services:
  crasher:
    location: ./crasher
  runner:
    location: ./runner
