name: Example application
description: Demonstrates basic Exosphere application startup
version: '1.0'

bus:
  type: exocom
  version: 0.21.8

services:
  public:
    web:
      location: ./web-server
  private:
    users:
      namespace: mongo
      location: ./mongo-service
