name: _____serviceName_____
description: _____description_____

setup: npm install --loglevel error --depth 0
startup:
  command: ./node_modules/livescript/bin/lsc app
  online-text: HTML server is running

messages:
  sends:
  receives:
