type: web
description: says hello to the world, ignores .txt files when file watching
author: exospheredev

startup:
  command: node server.js
  online-text: web server running at port
restart:
  ignore:
    - "**/*.txt"

messages:
  sends:
  receives:
