name: Application with end-to-end tests
description: Allows to run application tests
version: 1.0

bus:
  type: exocom
  version: latest

services:
  public:
    tweets-service:
      location: ./tweets-service
    users-service:
      location: ./users-service
