name: Application with end-to-end tests
description: Allows to run application tests
version: 1.0

services:
  public:
    tweets-service:
      location: ./tweets-service
      docker_image: exospheredev/another-service-with-tests-passing
    users-service:
      location: ./users-service
      docker_image: exospheredev/a-service-with-tests-passing
