type: _____serviceName_____
description: _____description_____
author: _____author_____

setup: yarn install
startup:
  command: node node_modules/exoservice/bin/exo-js
  online-text: online at port
tests: node_modules/cucumber/bin/cucumber.js

messages:
  receives:
    - ping
  sends:
    - pong

dependencies:
